Gh 110 switch CI to GitHub actions
gchq/gaffer-docker pull request #113
Opened 2020-11-04 18:05 UTC by d47853

2020-11-12 16:17 UTC, t11947 requested changes

2020-11-12 16:17 UTC, t11947 commented on cd/publish_images.sh
> +# This set's the values for:
```suggestion
# This sets the values for:
```

2020-11-16 11:24 UTC, d47853 commented
Closing while new failure is investigated

2020-11-16 15:06 UTC, ctas582 approved these changes

2020-11-16 15:07 UTC, merged