make NetworkPolicy installation optional
gchq/gaffer-docker pull request #157
Opened 2021-03-12 11:00 UTC by ahmetkaftan

closes #156 
Signed-off-by: Ahmet Kaftan <ahmet.kaftan@cloudnesil.com>

2021-03-12 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gchq/gaffer-docker?pullRequest=157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gchq/gaffer-docker?pullRequest=157) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gchq/gaffer-docker?pullRequest=157) it.</sub>

2021-03-23 16:00 UTC, t92549 requested changes

2021-03-23 16:43 UTC, t92549 commented
Would it be more useful to offer a way to change the network policy instead of disabling it entirely? For example, you could offer a way to change the `podSelector` to match more pods or even whitelist some IPs using an `ipBlock`. This would mean the hdfs nodes are still secure but they can be altered to match application needs.

2021-03-24 06:52 UTC, ahmetkaftan commented on kubernetes/hdfs/Chart.yaml
> +version: 0.10.1 # managed version
Reverted version bump

2021-03-24 06:52 UTC, ahmetkaftan commented on kubernetes/hdfs/values.yaml
> +  ## Specifies whether a NetworkPolicies should be created
Removed comment.

2021-03-24 06:54 UTC, ahmetkaftan commented
> Would it be more useful to offer a way to change the network policy instead of disabling it entirely? For example, you could offer a way to change the `podSelector` to match more pods or even whitelist some IPs using an `ipBlock`. This would mean the hdfs nodes are still secure but they can be altered to match application needs.

Yes, that's would be great but what if I or someone else handle this as a separate issue?

2021-03-24 11:03 UTC, t92549 approved these changes

2021-03-24 11:05 UTC, t92549 approved these changes

2021-03-24 12:50 UTC, t92549 commented
> > Would it be more useful to offer a way to change the network policy instead of disabling it entirely? For example, you could offer a way to change the `podSelector` to match more pods or even whitelist some IPs using an `ipBlock`. This would mean the hdfs nodes are still secure but they can be altered to match application needs.
> 
> Yes, that's would be great but what if I or someone else handle this as a separate issue?

Okay well we will merge this now but yes it would be nice to make this into another issue.

2021-03-24 12:51 UTC, merged