Update Gaffer version to 2.0.0-alpha-0.4
gchq/gaffer-docker pull request #289
Opened 2023-03-24 13:58 UTC by t92549

# Related Issue

- Resolve #285

2023-03-24 20:12 UTC, GCHQDeveloper314 requested changes
A file needs fixing.
Also, have you tested locally that the change from `GAFFER_TOOLS_VERSION` to `GAFFERPY_VERSION` is ok?

2023-03-24 20:12 UTC, GCHQDeveloper314 commented on docker/gaffer-operation-runner/operation-runner/target/classes/uk/gov/gchq/gaffer/docker/App.class
I think this is a mistake?

2023-03-27 11:53 UTC, t92549 commented
Have tested locally (and CI confirms) it works okay

2023-03-28 10:36 UTC, GCHQDeveloper314 approved these changes

2023-03-28 11:30 UTC, merged